import { FileText, Download, Printer, X, Clock, User } from 'lucide-react';
import React from 'react';
import { toast } from 'sonner';

import type { RecentReport } from '@/components/reports/RecentReportsCard';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Sheet,
    SheetContent,
} from '@/components/ui/sheet';

interface ReportsDrawerProps {
    report: RecentReport | null;
    open: boolean;
    onClose: () => void;
}

export function ReportsDrawer({ report, open, onClose }: ReportsDrawerProps) {
    if (!report) return null;

    const handleDownload = () => {
        toast.success(`Downloading ${report.name}...`);
    };

    return (
        <Sheet open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
            <SheetContent className="w-full sm:max-w-md p-0 bg-white dark:bg-[#121218] border-l border-[#F8C8DC]/60 dark:border-white/10 text-[#3D2C2E] dark:text-[#F8FAFC] font-['Outfit'] flex flex-col justify-between shadow-2xl">
                
                {/* Header */}
                <div className="p-6 bg-[#FFF5F7]/80 dark:bg-[#181824]/80 border-b border-[#F8C8DC]/60 dark:border-white/10 backdrop-blur-md space-y-4 shrink-0">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="size-11 rounded-2xl bg-white dark:bg-[#20202C] text-[#E75480] dark:text-[#FF4F81] border border-[#F8C8DC]/60 dark:border-white/10 flex items-center justify-center shadow-xs">
                                <FileText className="size-5" />
                            </div>
                            <div>
                                <h2 className="text-sm font-mono font-black text-[#E75480] dark:text-[#FF4F81]">
                                    {report.id}
                                </h2>
                                <h3 className="text-base font-extrabold text-[#3D2C2E] dark:text-[#F8FAFC] line-clamp-1">
                                    {report.name}
                                </h3>
                            </div>
                        </div>

                        <button
                            type="button"
                            onClick={onClose}
                            className="size-8 rounded-xl bg-white dark:bg-[#20202C] text-[#7D6B6E] dark:text-[#94A3B8] border border-[#F8C8DC]/60 dark:border-white/10 flex items-center justify-center hover:text-[#E75480] dark:hover:text-[#FF4F81] transition-colors cursor-pointer"
                        >
                            <X className="size-4" />
                        </button>
                    </div>

                    <div className="flex items-center justify-between gap-2 pt-1">
                        <Badge className="bg-[#FFF5F7] dark:bg-[#1C1C28] text-[#3D2C2E] dark:text-[#E2E8F0] border border-[#F8C8DC]/60 dark:border-white/10 font-bold uppercase text-[10px]">
                            {report.category}
                        </Badge>

                        <Badge className="bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-900/50 font-bold uppercase text-[10px]">
                            {report.status}
                        </Badge>
                    </div>
                </div>

                {/* Body Content */}
                <div className="flex-1 overflow-y-auto p-6 space-y-6">
                    
                    {/* Metadata Card */}
                    <div className="p-4 rounded-3xl bg-[#FFF5F7]/60 dark:bg-[#181820]/60 border border-[#F8C8DC]/40 dark:border-white/10 space-y-3 text-xs">
                        <div className="flex items-center justify-between text-[#7D6B6E] dark:text-[#94A3B8] font-bold">
                            <span className="flex items-center gap-1.5">
                                <User className="size-3.5" />
                                Generated By
                            </span>
                            <span className="text-[#3D2C2E] dark:text-[#F8FAFC] font-extrabold">{report.generatedBy}</span>
                        </div>
                        <div className="flex items-center justify-between text-[#7D6B6E] dark:text-[#94A3B8] font-bold">
                            <span className="flex items-center gap-1.5">
                                <Clock className="size-3.5" />
                                Timestamp
                            </span>
                            <span className="text-[#3D2C2E] dark:text-[#F8FAFC] font-mono font-bold">{report.generatedAt}</span>
                        </div>
                        <div className="flex items-center justify-between text-[#7D6B6E] dark:text-[#94A3B8] font-bold">
                            <span>Format & Size</span>
                            <span className="text-[#3D2C2E] dark:text-[#F8FAFC] font-mono font-bold uppercase">{report.fileType} ({report.fileSize})</span>
                        </div>
                    </div>

                    {/* Preview Summary */}
                    <div className="space-y-3">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-[#7D6B6E] dark:text-[#94A3B8]">
                            Report Executive Summary
                        </h4>

                        <div className="p-4 rounded-3xl border border-[#F8C8DC]/60 dark:border-white/10 bg-white dark:bg-[#181820] space-y-3 text-xs leading-relaxed text-[#3D2C2E] dark:text-[#E2E8F0]">
                            <p>
                                This telemetry report contains audit-ready data compiled from system POS registers and ingredient stock tracking modules.
                            </p>
                            <div className="p-3 rounded-2xl bg-[#FFF5F7] dark:bg-[#121218] border border-[#F8C8DC]/40 dark:border-white/10 space-y-1 font-mono text-[11px]">
                                <div className="flex justify-between">
                                    <span>Telemetry Integrity:</span>
                                    <span className="font-bold text-emerald-600 dark:text-emerald-400">100% Verified</span>
                                </div>
                                <div className="flex justify-between">
                                    <span>Branch Coverage:</span>
                                    <span className="font-bold">Multi-Branch Sync</span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                {/* Footer Controls */}
                <div className="p-6 bg-[#FFF5F7]/80 dark:bg-[#181824]/80 border-t border-[#F8C8DC]/60 dark:border-white/10 backdrop-blur-md flex items-center justify-between gap-3 shrink-0">
                    <Button
                        type="button"
                        variant="outline"
                        onClick={() => window.print()}
                        className="flex-1 h-11 rounded-2xl border-[#F8C8DC]/60 dark:border-white/10 bg-white dark:bg-[#181820] text-[#3D2C2E] dark:text-[#E2E8F0] hover:bg-[#FFF5F7] text-xs font-bold gap-2 cursor-pointer"
                    >
                        <Printer className="size-4 text-[#E75480] dark:text-[#FF4F81]" />
                        <span>Print Report</span>
                    </Button>

                    <Button
                        type="button"
                        onClick={handleDownload}
                        className="flex-1 h-11 rounded-2xl bg-[#E75480] dark:bg-[#E1062C] hover:bg-[#D43F6B] text-white text-xs font-bold gap-2 cursor-pointer shadow-xs"
                    >
                        <Download className="size-4" />
                        <span>Download {report.fileType.toUpperCase()}</span>
                    </Button>
                </div>

            </SheetContent>
        </Sheet>
    );
}
