<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class DynamicExport implements FromArray, WithStyles, WithTitle, ShouldAutoSize
{
    private $payload;

    public function __construct(array $payload)
    {
        $this->payload = $payload;
    }

    public function array(): array
    {
        $data = [];
        
        // 1. Report Title Section
        $data[] = [strtoupper($this->payload['reportName'] ?? 'REPORT')];
        $data[] = ['Company Name:', 'Maki Desu Operations Console'];
        $data[] = ['Branch Location:', $this->payload['branch'] ?? 'All Branches'];
        $data[] = ['Dataset Period:', $this->payload['dateRange'] ?? 'All Time'];
        $data[] = ['Generated By:', $this->payload['generatedBy'] ?? 'System Administrator'];
        $data[] = ['Generation Date:', date('Y-m-d H:i:s')];
        $data[] = []; // Spacer row

        // 2. KPI Summary Cards
        if (!empty($this->payload['kpis'])) {
            $data[] = ['KPI METRICS SUMMARY'];
            foreach ($this->payload['kpis'] as $kpi) {
                $data[] = [$kpi['title'] ?? '', $kpi['value'] ?? ''];
            }
            $data[] = []; // Spacer row
        }

        // 3. Columns Headers
        $headers = [];
        foreach ($this->payload['columns'] as $col) {
            $headers[] = $col['title'] ?? '';
        }
        $data[] = $headers;

        // 4. Data Rows
        foreach ($this->payload['rows'] as $row) {
            $rowData = [];
            foreach ($this->payload['columns'] as $col) {
                $key = $col['key'] ?? '';
                $rowData[] = $row[$key] ?? '';
            }
            $data[] = $rowData;
        }

        return $data;
    }

    public function styles(Worksheet $sheet)
    {
        // Calculate header position dynamically
        $kpiOffset = 8;
        if (!empty($this->payload['kpis'])) {
            $kpiOffset += count($this->payload['kpis']) + 2;
        }
        
        $headerRow = $kpiOffset - 1;
        $highestColumn = $sheet->getHighestColumn();
        $highestRow = $sheet->getHighestRow();

        // Freeze panes directly under header
        $sheet->freezePane("A" . ($headerRow + 1));

        // Format Title block
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14)->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color('E1062C'));

        // Format Main headers
        $sheet->getStyle("A{$headerRow}:{$highestColumn}{$headerRow}")->getFont()->setBold(true);
        $sheet->getStyle("A{$headerRow}:{$highestColumn}{$headerRow}")->getFill()
            ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
            ->getStartColor()->setARGB('FFF1F5F9'); // Slate bg

        // Clean grid borders
        $styleArray = [
            'borders' => [
                'allBorders' => [
                    'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => ['argb' => 'FFE2E8F0'],
                ],
            ],
        ];
        $sheet->getStyle("A{$headerRow}:{$highestColumn}{$highestRow}")->applyFromArray($styleArray);

        // Enable worksheet protection so exported performance files are locked/read-only
        $sheet->getProtection()->setSheet(true);
        $sheet->getProtection()->setPassword(bin2hex(random_bytes(8)));
    }

    public function title(): string
    {
        return $this->payload['reportName'] ?? 'Report';
    }
}
