<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $payload['reportName'] ?? 'Report' }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #1e293b;
            font-size: 10px;
            line-height: 1.4;
            margin: 0;
            padding: 10px;
        }
        .header {
            margin-bottom: 20px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
        }
        .title {
            font-size: 18px;
            font-weight: 900;
            text-transform: uppercase;
            color: #0f172a;
            margin: 0;
        }
        .meta-table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }
        .meta-table td {
            padding: 4px 0;
            vertical-align: top;
        }
        .meta-label {
            color: #64748b;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8px;
        }
        .kpi-container {
            margin-bottom: 25px;
            width: 100%;
        }
        .kpi-card {
            display: inline-block;
            width: 30%;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 10px;
            border-radius: 8px;
            margin-right: 2%;
            margin-bottom: 10px;
            vertical-align: top;
        }
        .kpi-title {
            font-size: 8px;
            text-transform: uppercase;
            color: #64748b;
            font-weight: bold;
            letter-spacing: 0.05em;
        }
        .kpi-value {
            font-size: 14px;
            font-weight: 800;
            color: #0f172a;
            margin-top: 4px;
        }
        .chart-container {
            text-align: center;
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        .chart-img {
            max-width: 100%;
            max-height: 250px;
            border: 1px solid #e2e8f0;
            padding: 4px;
            border-radius: 8px;
            background-color: #ffffff;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            page-break-inside: auto;
            table-layout: auto;
        }
        table.data-table tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }
        table.data-table th {
            background-color: #f1f5f9;
            color: #475569;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 7px;
            padding: 6px 4px;
            border: 1px solid #e2e8f0;
            letter-spacing: 0.02em;
            word-wrap: break-word;
        }
        table.data-table td {
            padding: 5px 4px;
            border: 1px solid #e2e8f0;
            color: #334155;
            font-size: 7.5px;
            word-wrap: break-word;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 20px;
            font-size: 8px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 5px;
        }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>
    <!-- Executive Cover Section -->
    <div class="header">
        <div class="title">{{ $payload['reportName'] ?? 'Report' }}</div>
        <div style="font-size: 10px; color: #64748b; margin-top: 4px; font-weight: bold; uppercase">Maki Desu Operations Intelligence</div>
    </div>

    <table class="meta-table">
        <tr>
            <td width="18%"><span class="meta-label">Branch Location:</span></td>
            <td width="32%">{{ $payload['branch'] ?? 'All Branches' }}</td>
            <td width="18%"><span class="meta-label">Date Generated:</span></td>
            <td width="32%">{{ date('Y-m-d H:i:s') }}</td>
        </tr>
        <tr>
            <td><span class="meta-label">Dataset Period:</span></td>
            <td>{{ $payload['dateRange'] ?? 'All Time' }}</td>
            <td><span class="meta-label">Generated By:</span></td>
            <td>{{ $payload['generatedBy'] ?? 'System Administrator' }}</td>
        </tr>
    </table>

    @if(!empty($payload['kpis']))
    <div class="kpi-container">
        @foreach($payload['kpis'] as $kpi)
        <div class="kpi-card">
            <div class="kpi-title">{{ $kpi['title'] }}</div>
            <div class="kpi-value">{{ $kpi['value'] }}</div>
        </div>
        @endforeach
    </div>
    @endif

    @if(!empty($payload['chartImage']) && (!isset($payload['includeCharts']) || $payload['includeCharts'] == true))
    <div class="chart-container">
        <img class="chart-img" src="{{ $payload['chartImage'] }}" />
    </div>
    @endif

    <table class="data-table">
        <thead>
            <tr>
                @foreach($payload['columns'] as $col)
                <th class="{{ $col['align'] ?? '' }}">{{ $col['title'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($payload['rows'] as $row)
            <tr>
                @foreach($payload['columns'] as $col)
                <td class="{{ $col['align'] ?? '' }}">
                    {{ $row[$col['key']] ?? '' }}
                </td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <table width="100%">
            <tr>
                <td style="font-weight: bold; text-transform: uppercase;">CONFIDENTIAL · FOR INTERNAL BUSINESS USE ONLY</td>
                <td class="text-right">Page <span class="page-number"></span></td>
            </tr>
        </table>
    </div>
</body>
</html>
