import { Form, Head } from '@inertiajs/react';
import { ShieldBan, ShieldCheck } from 'lucide-react';
import React, { useState } from 'react';

import TwoFactorRecoveryCodes from '@/components/two-factor-recovery-codes';
import TwoFactorSetupModal from '@/components/two-factor-setup-modal';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { useTwoFactorAuth } from '@/hooks/use-two-factor-auth';
import SettingsLayout from '@/layouts/settings/layout';
import { disable, enable } from '@/routes/two-factor';

type Props = {
    requiresConfirmation?: boolean;
    twoFactorEnabled?: boolean;
};

export default function TwoFactor({
    requiresConfirmation = false,
    twoFactorEnabled = false,
}: Props) {
    const {
        qrCodeSvg,
        hasSetupData,
        manualSetupKey,
        clearSetupData,
        fetchSetupData,
        recoveryCodesList,
        fetchRecoveryCodes,
        errors,
    } = useTwoFactorAuth();
    const [showSetupModal, setShowSetupModal] = useState<boolean>(false);

    return (
        <SettingsLayout>
            <Head title="Two-Factor Authentication" />

            <div className="space-y-8 font-['Outfit']">
                {/* Header */}
                <div className="space-y-1 border-b border-[#F8C8DC]/40 dark:border-white/10 pb-6">
                    <div className="flex items-center gap-3">
                        <h2 className="text-xl font-black text-[#3D2C2E] dark:text-[#F8FAFC]">
                            Two-Factor Authentication (2FA)
                        </h2>
                        {twoFactorEnabled ? (
                            <Badge className="bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 text-xs font-bold">
                                Enabled
                            </Badge>
                        ) : (
                            <Badge variant="destructive" className="text-xs font-bold">
                                Disabled
                            </Badge>
                        )}
                    </div>
                    <p className="text-xs text-[#7D6B6E] dark:text-[#94A3B8] font-medium">
                        Add an extra layer of security to your account using TOTP authenticator applications.
                    </p>
                </div>

                {twoFactorEnabled ? (
                    <div className="space-y-6">
                        <div className="p-5 rounded-3xl bg-emerald-500/5 dark:bg-emerald-950/20 border border-emerald-500/20 flex items-start gap-4">
                            <div className="p-3 rounded-2xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 shrink-0">
                                <ShieldCheck className="size-6" />
                            </div>
                            <div className="space-y-1">
                                <h4 className="text-sm font-bold text-[#3D2C2E] dark:text-[#F8FAFC]">
                                    Account Security Active
                                </h4>
                                <p className="text-xs text-[#7D6B6E] dark:text-[#94A3B8] font-medium leading-relaxed">
                                    With 2FA active, login requests will require a time-based 6-digit passcode generated by your authenticator app (Google Authenticator, 1Password, etc.).
                                </p>
                            </div>
                        </div>

                        <TwoFactorRecoveryCodes
                            recoveryCodesList={recoveryCodesList}
                            fetchRecoveryCodes={fetchRecoveryCodes}
                            errors={errors}
                        />

                        <div className="pt-2">
                            <Form {...disable.form()}>
                                {({ processing }) => (
                                    <Button
                                        variant="destructive"
                                        type="submit"
                                        disabled={processing}
                                        className="h-11 px-6 rounded-2xl font-bold text-xs uppercase tracking-wider bg-rose-600 hover:bg-rose-700 text-white cursor-pointer gap-2"
                                    >
                                        <ShieldBan className="size-4" />
                                        <span>Disable 2FA</span>
                                    </Button>
                                )}
                            </Form>
                        </div>
                    </div>
                ) : (
                    <div className="space-y-6">
                        <div className="p-5 rounded-3xl bg-amber-500/5 dark:bg-amber-950/20 border border-amber-500/20 flex items-start gap-4">
                            <div className="p-3 rounded-2xl bg-amber-500/10 text-amber-600 dark:text-amber-400 shrink-0">
                                <ShieldBan className="size-6" />
                            </div>
                            <div className="space-y-1">
                                <h4 className="text-sm font-bold text-[#3D2C2E] dark:text-[#F8FAFC]">
                                    Two-Factor Authentication Disabled
                                </h4>
                                <p className="text-xs text-[#7D6B6E] dark:text-[#94A3B8] font-medium leading-relaxed">
                                    Enabling two-factor authentication protects your account from unauthorized password access by requiring a TOTP code during authentication.
                                </p>
                            </div>
                        </div>

                        <div>
                            {hasSetupData ? (
                                <Button
                                    onClick={() => setShowSetupModal(true)}
                                    className="h-11 px-6 rounded-2xl font-black text-xs uppercase tracking-wider bg-[#E75480] hover:bg-[#D43F6B] text-white cursor-pointer gap-2"
                                >
                                    <ShieldCheck className="size-4" />
                                    <span>Continue 2FA Setup</span>
                                </Button>
                            ) : (
                                <Form
                                    {...enable.form()}
                                    onSuccess={() => setShowSetupModal(true)}
                                >
                                    {({ processing }) => (
                                        <Button
                                            type="submit"
                                            disabled={processing}
                                            className="h-11 px-6 rounded-2xl font-black text-xs uppercase tracking-wider bg-[#E75480] hover:bg-[#D43F6B] text-white cursor-pointer gap-2"
                                        >
                                            <ShieldCheck className="size-4" />
                                            <span>Enable 2FA Protection</span>
                                        </Button>
                                    )}
                                </Form>
                            )}
                        </div>
                    </div>
                )}

                <TwoFactorSetupModal
                    isOpen={showSetupModal}
                    onClose={() => setShowSetupModal(false)}
                    requiresConfirmation={requiresConfirmation}
                    twoFactorEnabled={twoFactorEnabled}
                    qrCodeSvg={qrCodeSvg}
                    manualSetupKey={manualSetupKey}
                    clearSetupData={clearSetupData}
                    fetchSetupData={fetchSetupData}
                    errors={errors}
                />
            </div>
        </SettingsLayout>
    );
}
