<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Models\User;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;

class EmployeeController extends Controller
{
    public function index()
    {
        $viewer = Auth::user();

        $employeeQuery = User::with('branch')
            ->manageableEmployees($viewer);

        $employees = (clone $employeeQuery)
            ->latest()
            ->get();

        // Calculate authoritative backend KPIs matching the visible roster definition:
        // Rule: ADMINISTRATORS KPI counts active ADMIN accounts ONLY (User::ROLE_ADMIN).
        // SUPER_ADMIN is strictly EXCLUDED from the administrators count and total count when viewed by Admin.
        $activeQuery = (clone $employeeQuery)->where(function ($q) {
            $q->whereNull('account_status')->orWhere('account_status', '!=', User::STATUS_DEACTIVATED);
        });

        $kpis = [
            'total'             => (clone $activeQuery)->count(),
            'admins'            => (clone $activeQuery)->where('role', User::ROLE_ADMIN)->count(),
            'cashiers'          => (clone $activeQuery)->where('role', User::ROLE_CASHIER)->count(),
            'assigned_branches' => (clone $activeQuery)->whereNotNull('branch_id')->distinct('branch_id')->count('branch_id'),
        ];

        return Inertia::render('Admin/Employees/Index', [
            'employees'    => $employees,
            'branches'     => Branch::orderBy('name')->get(),
            'kpis'         => $kpis,
            'isSuperAdmin' => (bool) $viewer?->isSuperAdmin(),
        ]);
    }

    public function store(Request $request)
    {
        $viewer = Auth::user();

        // Block privilege escalation: Only Super Admin can create Super Admin
        if ($request->input('role') === User::ROLE_SUPER_ADMIN && (!$viewer || !$viewer->isSuperAdmin())) {
            abort(403, 'Unauthorized: You do not have permission to create a Super Admin account.');
        }

        if ($request->has('email')) {
            $request->merge(['email' => strtolower(trim($request->input('email')))]);
        }
        if ($request->has('name')) {
            $request->merge(['name' => trim($request->input('name'))]);
        }

        $allowedRoles = ($viewer && $viewer->isSuperAdmin())
            ? 'admin,cashier,super_admin'
            : 'admin,cashier';

        $validated = $request->validate([
            'name' => [
                'required',
                'string',
                'min:2',
                'max:50',
                'regex:/^[A-Za-z\s]+$/'
            ],
            'email'     => 'required|string|email|max:100|unique:users',
            'password'  => 'nullable|string|min:8|max:100',
            'role'      => 'required|string|in:' . $allowedRoles,
            'branch_id' => 'required|exists:branches,id',
        ], [
            'name.required' => 'Full name is required.',
            'name.min'      => 'Full name must be at least 2 characters.',
            'name.max'      => 'Full name cannot exceed 50 characters.',
            'name.regex'    => 'Full name must only contain letters and spaces.',
            'branch_id.required' => 'Please select an assigned branch.',
        ]);

        // Generate password if not provided
        $wasAutoGenerated = !$request->filled('password');
        $plainPassword = $wasAutoGenerated
            ? \Illuminate\Support\Str::password(12, letters: true, numbers: true, symbols: false)
            : $request->password;

        $user = User::create([
            'name'                 => $validated['name'],
            'email'                => $validated['email'],
            'password'             => Hash::make($plainPassword),
            'role'                 => $validated['role'],
            'branch_id'            => $validated['branch_id'] ?? null,
            'must_change_password' => true,
        ]);

        // Send Email
        $emailSent = false;
        try {
            \Illuminate\Support\Facades\Mail::to($user->email)->send(
                new \App\Mail\EmployeeCredentialsMail($user->name, $user->email, $plainPassword)
            );
            $emailSent = true;
        } catch (\Throwable $e) {
            \Illuminate\Support\Facades\Log::error('Failed to send employee credentials email: ' . $e->getMessage());
        }

        return back()->with([
            'success' => 'Employee created successfully' . ($emailSent ? ' and credentials emailed.' : '.'),
            'new_employee' => [
                'name'           => $user->name,
                'email'          => $user->email,
                'password'       => $plainPassword,
                'auto_generated' => $wasAutoGenerated,
                'email_sent'     => $emailSent,
            ]
        ]);
    }

    public function update(Request $request, User $employee)
    {
        $viewer = Auth::user();

        // Security Gate: Non-super-admins cannot view or modify Super Admin accounts
        if ($employee->isSuperAdmin() && (!$viewer || !$viewer->isSuperAdmin())) {
            abort(403, 'Unauthorized: You cannot modify a Super Admin account.');
        }

        // Block privilege escalation: Non-super-admins cannot promote users to Super Admin
        if ($request->input('role') === User::ROLE_SUPER_ADMIN && (!$viewer || !$viewer->isSuperAdmin())) {
            abort(403, 'Unauthorized: You do not have permission to assign the Super Admin role.');
        }

        if ($request->has('email')) {
            $request->merge(['email' => strtolower(trim($request->input('email')))]);
        }
        if ($request->has('name')) {
            $request->merge(['name' => trim($request->input('name'))]);
        }

        $allowedRoles = ($viewer && $viewer->isSuperAdmin())
            ? 'admin,cashier,super_admin'
            : 'admin,cashier';

        $validated = $request->validate([
            'name' => [
                'required',
                'string',
                'min:2',
                'max:50',
                'regex:/^[A-Za-z\s]+$/'
            ],
            'email'     => 'required|string|email|max:100|unique:users,email,' . $employee->id,
            'password'  => 'nullable|string|min:8|max:100',
            'role'      => 'required|string|in:' . $allowedRoles,
            'branch_id' => 'required|exists:branches,id',
        ], [
            'name.required' => 'Full name is required.',
            'name.min'      => 'Full name must be at least 2 characters.',
            'name.max'      => 'Full name cannot exceed 50 characters.',
            'name.regex'    => 'Full name must only contain letters and spaces.',
            'branch_id.required' => 'Please select an assigned branch.',
        ]);

        $employee->update([
            'name'      => $validated['name'],
            'email'     => $validated['email'],
            'role'      => $validated['role'],
            'branch_id' => $validated['branch_id'] ?? null,
        ]);

        if ($request->filled('password')) {
            $employee->update(['password' => Hash::make($validated['password'])]);
        }

        return back()->with('success', 'Employee updated successfully');
    }

    public function destroy(User $employee)
    {
        $viewer = Auth::user();

        // Security Gate: Non-super-admins cannot delete Super Admin accounts
        if ($employee->isSuperAdmin() && (!$viewer || !$viewer->isSuperAdmin())) {
            abort(403, 'Unauthorized: You cannot delete a Super Admin account.');
        }

        if ($employee->id === Auth::id()) {
            return back()->with('error', 'You cannot delete yourself');
        }

        $employee->delete();
        return back()->with('success', 'Employee deleted successfully');
    }
}
