<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Rider;
use App\Models\Branch;
use App\Mail\RiderCredentialsMail;
use App\Events\RiderStatusUpdated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Inertia\Inertia;

class RiderController extends Controller
{
    public function index(Request $request)
    {
        $query = Rider::with('branch')->withCount('deliveries');

        if ($request->filled('branch_id') && $request->input('branch_id') !== 'all') {
            $query->where('branch_id', $request->input('branch_id'));
        }

        if ($request->filled('status') && $request->input('status') !== 'all') {
            $query->where('status', $request->input('status'));
        }

        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                    ->orWhere('phone', 'like', "%{$search}%")
                    ->orWhere('email', 'like', "%{$search}%");
            });
        }

        $riders = $query->latest()->paginate(15)->withQueryString();

        $stats = [
            'total'     => Rider::count(),
            'available' => Rider::where('status', 'available')->where('is_active', true)->count(),
            'busy'      => Rider::where('status', 'busy')->where('is_active', true)->count(),
            'offline'   => Rider::where(function ($q) {
                $q->where('status', 'offline')->orWhereNull('status');
            })->where('is_active', true)->count(),
        ];

        return Inertia::render('Admin/Riders/Index', [
            'riders' => $riders,
            'filters' => $request->only(['branch_id', 'status', 'search']),
            'branches' => Branch::orderBy('name')->get(['id', 'name']),
            'stats' => $stats,
        ]);
    }

    public function store(Request $request)
    {
        // Normalize email input before validation
        if ($request->has('email')) {
            $request->merge(['email' => strtolower(trim($request->input('email')))]);
        }

        $validated = $request->validate([
            'name'      => 'required|string|max:255',
            'email'     => ['required', 'email', Rule::unique('riders', 'email')->whereNull('deleted_at')],
            'phone'     => ['nullable', 'string', 'max:20', 'regex:/^[\+]?[0-9\s\-\(\)]{7,20}$/'],
            'branch_id' => 'required|exists:branches,id',
            'password'  => 'nullable|string|min:6',
        ], [
            'email.unique' => 'The email is already associated with an active rider account.',
        ]);

        // ── Password Logic ─────────────────────────────────────────
        $wasAutoGenerated = !$request->filled('password');
        $plainPassword = $wasAutoGenerated
            ? Str::password(10, letters: true, numbers: true, symbols: false)
            : $request->password;

        $validated['password'] = Hash::make($plainPassword);
        $validated['role'] = 'rider';
        $validated['is_active'] = true;
        $validated['status'] = 'offline'; // Force default offline for new accounts

        $rider = Rider::create($validated);

        // ── Email Notification ─────────────────────────────────────
        $emailSent = false;
        try {
            Mail::to($rider->email)->send(
                new RiderCredentialsMail($rider->name, $rider->email, $plainPassword)
            );
            $emailSent = true;
            Log::info('Rider credentials email sent', ['rider_id' => $rider->id, 'email' => $rider->email]);
        } catch (\Throwable $e) {
            Log::warning('Failed to send rider credentials email', [
                'rider_id' => $rider->id,
                'email' => $rider->email,
                'error' => $e->getMessage(),
            ]);
        }

        return back()->with([
            'success' => 'Rider added successfully.' . ($emailSent ? ' Credentials sent to ' . $rider->email : ''),
            'new_rider' => [
                'name' => $rider->name,
                'email' => $rider->email,
                'password' => $plainPassword,
                'auto_generated' => $wasAutoGenerated,
                'email_sent' => $emailSent,
            ]
        ]);
    }

    public function update(Request $request, Rider $rider)
    {
        // Normalize email input before validation
        if ($request->has('email')) {
            $request->merge(['email' => strtolower(trim($request->input('email')))]);
        }

        $validated = $request->validate([
            'name'      => 'required|string|max:255',
            'email'     => ['required', 'email', Rule::unique('riders', 'email')->ignore($rider->id)->whereNull('deleted_at')],
            'phone'     => ['nullable', 'string', 'max:20', 'regex:/^[\+]?[0-9\s\-\(\)]{7,20}$/'],
            'branch_id' => 'required|exists:branches,id',
            'password'  => 'nullable|string|min:6',
            'is_active' => 'required|boolean',
        ], [
            'email.unique' => 'The email is already associated with an active rider account.',
        ]);

        if ($request->filled('password')) {
            $validated['password'] = Hash::make($request->password);
        } else {
            unset($validated['password']);
        }

        if (!$validated['is_active']) {
            $validated['status'] = 'offline';
        } elseif ($validated['is_active'] && $rider->status === 'offline') {
            $validated['status'] = 'available';
        }

        $rider->update($validated);

        try {
            event(new RiderStatusUpdated($rider->fresh(['branch'])));
        } catch (\Throwable $e) {
            Log::warning('RiderStatusUpdated broadcast failed: ' . $e->getMessage());
        }

        return back()->with('success', 'Rider updated successfully.');
    }

    public function destroy(Request $request, Rider $rider)
    {
        // 1. Guard against deleting rider with active, non-terminal deliveries
        $hasActiveDeliveries = $rider->deliveries()
            ->whereNotIn('status', ['delivered', 'cancelled'])
            ->exists();

        if ($hasActiveDeliveries) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error' => 'Rider cannot be removed while active deliveries are assigned. Please complete or reassign active deliveries first.'
                ], 422);
            }
            return back()->with('error', 'Rider cannot be removed while active deliveries are assigned. Please complete or reassign active deliveries first.');
        }

        // 2. Revoke all active API authentication tokens
        try {
            $rider->tokens()->delete();
        } catch (\Throwable $e) {
            Log::warning('Failed to revoke tokens on rider retirement: ' . $e->getMessage());
        }

        // 3. Free up email for future active accounts while preserving historical delivery references & rider identity
        $retiredEmail = 'retired_' . $rider->id . '_' . time() . '_' . $rider->email;
        $rider->update([
            'email'     => $retiredEmail,
            'is_active' => false,
            'status'    => 'offline',
        ]);

        // 4. Soft delete rider record
        $rider->delete();

        try {
            event(new RiderStatusUpdated($rider->fresh(['branch'])));
        } catch (\Throwable $e) {
            Log::warning('RiderStatusUpdated broadcast failed: ' . $e->getMessage());
        }

        return back()->with('success', 'Rider removed successfully.');
    }

    /**
     * Returns available riders for a branch (used by POS AJAX).
     */
    public function available(Request $request)
    {
        $request->validate(['branch_id' => 'required|exists:branches,id']);

        $riders = Rider::where('branch_id', $request->input('branch_id'))
            ->availableForAssignment()
            ->get(['id', 'name', 'phone']);

        return response()->json($riders);
    }
}
