<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Rider;
use App\Models\Branch;
use App\Mail\RiderCredentialsMail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Inertia\Inertia;

class RiderController extends Controller
{
    public function index(Request $request)
    {
        $query = Rider::with('branch')->withCount('deliveries');

        if ($request->filled('branch_id') && $request->input('branch_id') !== 'all') {
            $query->where('branch_id', $request->input('branch_id'));
        }

        if ($request->filled('status') && $request->input('status') !== 'all') {
            $query->where('status', $request->input('status'));
        }

        if ($request->filled('search')) {
            $search = $request->input('search');
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('phone', 'like', "%{$search}%")
                  ->orWhere('email', 'like', "%{$search}%");
            });
        }

        $riders = $query->latest()->paginate(15)->withQueryString();

        $stats = [
            'total' => Rider::count(),
            'available' => Rider::where('status', 'available')->count(),
            'busy' => Rider::where('status', 'busy')->count(),
            'offline' => Rider::where('status', 'offline')->count(),
        ];

        return Inertia::render('Admin/Riders/Index', [
            'riders'   => $riders,
            'filters'  => $request->only(['branch_id', 'status', 'search']),
            'branches' => Branch::orderBy('name')->get(['id', 'name']),
            'stats'    => $stats,
        ]);
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name'      => 'required|string|max:255',
            'email'     => 'required|email|unique:riders,email',
            'phone'     => ['nullable', 'string', 'max:20', 'regex:/^[\+]?[0-9\s\-\(\)]{7,20}$/'],
            'branch_id' => 'required|exists:branches,id',
            'password'  => 'nullable|string|min:6',
        ]);

        // ── Password Logic ─────────────────────────────────────────
        // If admin left blank → generate a secure random password
        // If admin provided one → use it as-is (already validated min:6)
        $wasAutoGenerated = ! $request->filled('password');
        $plainPassword = $wasAutoGenerated
            ? Str::password(10, letters: true, numbers: true, symbols: false)
            : $request->password;

        $validated['password'] = Hash::make($plainPassword);
        $validated['role'] = 'rider';
        $validated['is_active'] = true;
        $validated['status'] = 'offline'; // Force default offline for new accounts
        $validated['must_change_password'] = true;

        $rider = Rider::create($validated);

        // ── Email Notification ─────────────────────────────────────
        // Send credentials to the rider's email. Wrapped in try/catch
        // so a mail server issue never blocks account creation.
        $emailSent = false;
        try {
            Mail::to($rider->email)->send(
                new RiderCredentialsMail($rider->name, $rider->email, $plainPassword)
            );
            $emailSent = true;
            Log::info('Rider credentials email sent', ['rider_id' => $rider->id, 'email' => $rider->email]);
        } catch (\Throwable $e) {
            Log::warning('Failed to send rider credentials email', [
                'rider_id' => $rider->id,
                'email'    => $rider->email,
                'error'    => $e->getMessage(),
            ]);
        }

        return back()->with([
            'success' => 'Rider added successfully.' . ($emailSent ? ' Credentials sent to ' . $rider->email : ''),
            'new_rider' => [
                'name'           => $rider->name,
                'email'          => $rider->email,
                'password'       => $plainPassword,
                'auto_generated' => $wasAutoGenerated,
                'email_sent'     => $emailSent,
            ]
        ]);
    }

    public function update(Request $request, Rider $rider)
    {
        $validated = $request->validate([
            'name'      => 'required|string|max:255',
            'email'     => 'required|email|unique:riders,email,' . $rider->id,
            'phone'     => ['nullable', 'string', 'max:20', 'regex:/^[\+]?[0-9\s\-\(\)]{7,20}$/'],
            'branch_id' => 'required|exists:branches,id',
            'password'  => 'nullable|string|min:6',
            'is_active' => 'required|boolean',
        ]);

        if ($request->filled('password')) {
            $validated['password'] = Hash::make($request->password);
        } else {
            unset($validated['password']);
        }

        $rider->update($validated);

        return back()->with('success', 'Rider updated successfully.');
    }

    public function destroy(Rider $rider)
    {
        $rider->delete();
        return back()->with('success', 'Rider removed successfully.');
    }

    /**
     * Returns available riders for a branch (used by POS AJAX).
     */
    public function available(Request $request)
    {
        $request->validate(['branch_id' => 'required|exists:branches,id']);

        $riders = Rider::where('branch_id', $request->input('branch_id'))
            ->available()
            ->get(['id', 'name', 'phone']);

        return response()->json($riders);
    }
}
